# Generated by Django 6.0 on 2025-12-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='auction_item',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
    ]
