# Generated by Django 6.0 on 2026-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='auctions/'),
        ),
    ]
